import { Inter } from "next/font/google";
import "./globals.css";
import Chatbot from '@/components/universal/Chatbot'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agri Guardion 360",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Chatbot />
      </body>
    </html>
  );
}
